"""Exports the cast's art facts (canvases, hitboxes, shoot points, clip lists) to src/CastLayout.cs.

The C# never hard-codes a pixel number that the art decides: tech_poses.py, nurse_poses.py and npc_poses.py own them,
this module writes them out, and tools/validate.py fails the build when the generated file is stale.
"""
import os
import types
from collections import OrderedDict

import tech_poses as T
import nurse_poses as N
import vet_poses as VP
import npc_poses as NP
import art_sources

ENEMY_ROOT = 'PlutoVetVisit/Resources/Enemies'
NPC_ROOT = 'PlutoVetVisit/Resources/Npcs'
BOSS_ROOT = 'PlutoVetVisit/Resources/Boss'

# Placeable name -> art folder. The room places NPCs by these names (clinic_room.NPCS).
NPC_OBJECTS = OrderedDict([
    ('pluto_npc_bogdan', 'bogdan'),
    ('pluto_npc_bianca', 'bianca'),
    ('pluto_npc_receptionist', 'receptionist'),
    ('pluto_npc_rex', 'rex'),
    ('pluto_npc_grandma', 'grandma'),
])


def _enemy_block(prefix, module, folder, root=ENEMY_ROOT):
    w, h = module.CANVAS
    hx, hy, hw, hh = module.HITBOX
    sx, sy = module.SHOOT_POINT
    clips = list(module.CLIPS)
    return [
        '        public const string %s_ROOT = "%s/%s";' % (prefix, root, folder),
        '        public const int %s_W = %d, %s_H = %d;' % (prefix, w, prefix, h),
        '        public const int %s_HIT_X = %d, %s_HIT_Y = %d, %s_HIT_W = %d, %s_HIT_H = %d;' % (prefix, hx, prefix, hy, prefix, hw, prefix, hh),
        '        public const int %s_SHOOT_X = %d, %s_SHOOT_Y = %d;' % (prefix, sx, prefix, sy),
        '        public static readonly string[] %s_CLIPS = { %s };' % (prefix, ', '.join('"%s"' % c for c in clips)),
        '        public static readonly int[] %s_FRAMES = { %s };' % (prefix, ', '.join(str(len(module.CLIPS[c])) for c in clips)),
    ]


def layout_cs():
    lines = [
        '// GENERATED by tools/cast_layout.py from the pose modules. Do not edit by hand.',
        'namespace PlutoVetVisit',
        '{',
        '    public static class CastLayout',
        '    {',
        '        public const string NPC_ROOT = "%s";' % NPC_ROOT,
    ]
    lines += _enemy_block('TECH', T, 'tech')
    stech = types.SimpleNamespace(CANVAS=T.CANVAS, HITBOX=T.HITBOX, SHOOT_POINT=T.STECH_SHOOT_POINT, CLIPS=T.STECH_CLIPS)
    lines += _enemy_block('STECH', stech, 'stech')
    lines += _enemy_block('NURSE', N, 'nurse')
    lines += _enemy_block('VET', VP, 'vet', root=BOSS_ROOT)
    # 0.14.0: the masked last phase; frames come from approved art (art_sources.MASK_CLIPS)
    lines.append('        public static readonly string[] VET_MASK_CLIPS = { %s };' % ', '.join('"%s"' % c for c in art_sources.MASK_CLIPS))
    lines.append('        public static readonly int[] VET_MASK_FRAMES = { %s };' % ', '.join(str(n) for n in art_sources.MASK_CLIPS.values()))
    lines.append('        public static readonly NpcSpec[] NPCS = {')
    for name, who in NPC_OBJECTS.items():
        spec = NP.NPCS[who]
        w, h = spec['canvas']
        clips = list(spec['clips'])
        lines.append('            new NpcSpec("%s", "%s", %d, %d, new[] { %s }, new[] { %s }),'
                     % (name, who, w, h, ', '.join('"%s"' % c for c in clips), ', '.join(str(len(spec['clips'][c])) for c in clips)))
    lines += [
        '        };',
        '    }',
        '',
        '    public class NpcSpec',
        '    {',
        '        public string Name, Folder;',
        '        public int W, H;',
        '        public string[] Clips;',
        '        public int[] Frames;',
        '        public NpcSpec(string name, string folder, int w, int h, string[] clips, int[] frames)',
        '        {',
        '            Name = name; Folder = folder; W = w; H = h; Clips = clips; Frames = frames;',
        '        }',
        '    }',
        '}',
        '',
    ]
    return '\n'.join(lines)


def write(project):
    cs = os.path.join(project, 'src', 'CastLayout.cs')
    with open(cs, 'w') as fh:
        fh.write(layout_cs())
    return cs
