"""The past's win picture (115x71, shown on the Ammonomicon "YOU WON" page): a hand-drawn happy ending.

Alexandria's AmmonomiconDeathPageController.SetWinPic postfix only swaps photoSprite.Texture, so the game scales
this texture into the vanilla photo frame (about 5.25x at 1440p, with tape over the four corners): keep 115x71 and
keep the corners quiet.

Scene: Pluto triumphant on the exam table (paw up, tail up, mouth open), the Vet knocked out on the tiles with
dizzy stars, his syringe pistol dropped and a broken syringe leaking, and Pluto's owners Bogdan (short dark brown
hair, light stubble, navy top, jeans) and Bianca (long brown hair, yellow dress, arms open) walking in through the
lit doorway. Every figure is row-string art; only the flat wall and floor tiles are generated by loops.
"""
import os

from PIL import Image

import vetpixel as V
import vet_poses as VP
from pixel import overlay, pad, flip_h, check_rect as R

WIN = (115, 71)
WALL_H = 26            # rows 0..25 are the back wall, the floor starts at row 26

# ---------------------------------------------------------------- Pluto (30x24): front view, left paw up, tail up
PLUTO_TAIL = R([       # ringed tail held up with a hooked tip (tabby / near-black bands), drawn behind the body
    ".ooo...",
    "oLBBo..",
    "obbBBo.",
    ".ooobbo",
    "...obbo",
    "...oBBo",
    "...oBBo",
    "..obbo.",
    "..obbo.",
    "..oBBo.",
    ".oBBo..",
    ".obbo..",
    "obbo...",
    "oBo....",
    "oo.....",
])
PLUTO_BODY = R([       # 18 wide: head (12 rows), chest out (7), legs (3)
    "....oo......oo....",
    "...oBBo....oBBo...",
    "...oBPPoooooPPBo..",
    "..oBBPBBBBBBBPBBo.",
    ".oBbBBBBBBBBBBbBdo",
    ".oBBbBBBWWWBBBbBdo",
    ".oBBBBBBWWWBBBBBdo",
    ".oBBBgGBBBBBGgBBdo",
    ".oBBBgGBWWWBGgBBdo",
    ".oBWWWWWWWWWWWWWBo",
    ".oWWWWWWWPPWWWWWwo",
    "..oWWWWWoppoWWWwo.",   # open mouth: cheering
    "..oBBBWWWooWWBBBo.",
    ".oBBBWWWWWWWWWBBdo",
    ".oBbWWWWWWWWWWWbdo",
    ".oBbWWWWWWWWWWWbdo",
    ".oBBBWWWWWWWWWBBdo",
    ".oBBBWWWWwwwwBBBdo",
    "..oBBwwwwwwwwwBBo.",
    "...oWWo.....oWWo..",
    "...owwo.....owwo..",
    "....oo.......oo...",
])
PLUTO_ARM = R([        # raised foreleg, white paw with a pink bean
    ".ooo...",
    "oWWWo..",
    "oWqWo..",
    "owWwo..",
    ".oBBo..",
    ".obbo..",
    ".oBBo..",
    "..oBo..",
    "..obbo.",
    "..oBBo.",
    "...oBBo",
    "...obbo",
    "....oBB",
])


def pluto():
    canvas = pad(PLUTO_TAIL, 30, 24, 23, 4)
    canvas = overlay(canvas, PLUTO_BODY, 5, 2)
    return overlay(canvas, PLUTO_ARM, 1, 2)


# ---------------------------------------------------------------- Bogdan (14x27): short dark hair, stubble, navy, jeans
# Same colours as his in-game sprite (npc_poses.py). N / D / E stand for the navy hoodie's mid / shade / light
# ('O', '"', "'"): quote characters are unreadable inside row strings.
_NAVY = str.maketrans({'N': 'O', 'D': '"', 'E': "'"})
BOGDAN = R([r.translate(_NAVY) for r in [
    "....oooooo....",
    "...oXmmmXXo...",
    "..oXmmXXXXXo..",
    "..oXXXXXXXXXo.",
    "..oX@XXXX@XXo.",
    "..oX========o.",
    ".o-=Kg===Kg=-o",
    ".o-=========-o",
    "..o-=o===o=-o.",
    "...o;-ooo-;o..",
    "....o;-;-;o...",
    ".....o==o.....",
    "...oDDooNNo...",
    "..oDEENNNEEo..",
    ".oDENNNNNNNNo.",
    ".oDNNNNNNNNNo.",
    ".oDNNNNNNNNNo.",
    ".o=DNNNNNNNo=o",
    ".o-oDDDDDDDo-o",
    "..oo2||||||oo.",
    "...o2||/|||o..",
    "...o2|/o||/o..",
    "...o2|/o||/o..",
    "...o2|/o||/o..",
    "...o@@@o@@@o..",
    "..o@@@@o@@@@o.",
    "..ooooo.ooooo.",
]])

# ---------------------------------------------------------------- Bianca (20x24): long brown hair, yellow dress, arms open
BIANCA = R([
    ".......oooooo.......",
    "......ommMMmmo......",
    ".....ommMMmmmmo.....",
    "....ommMmmmmmmXo....",
    "....omMmm====mXo....",
    "....omm=======Xo....",
    "....omm=Kg=Kg=Xo....",
    "....omq=======qXo...",
    "....omm==ppp=-Xo....",
    "....ommo-===-omXo...",
    "....ommmoo=oommXo...",
    "...ommXoA::::aoXmo..",
    "...ommXoA::::aoXmo..",
    "....omXoA::::aoXo...",
    ".....ooAaaaaaaoo....",
    ".....oA:::::::ao....",
    "....oA:::::::::ao...",
    "....oA:::::::::ao...",
    "...oA:::::::::::ao..",
    "...ooaaaaaaaaaaaoo..",
    ".......o=o.o=o......",
    ".......o=o.o=o......",
    "......o++o.o++o.....",
    "......oooo.oooo.....",
])
BIANCA_ARM = R([       # left arm, open wide; the right arm is its mirror
    "oo....",
    "o=o...",
    ".o=o..",
    "..o=o.",
    "...o:o",
    "....o:",
])


def bianca():
    rows = pad(BIANCA, 24, 24, 2, 0)
    rows = overlay(rows, BIANCA_ARM, 0, 7)
    return overlay(rows, flip_h(BIANCA_ARM), 18, 7)


# ---------------------------------------------------------------- props and effects
HEART = R([
    ".o.o.",
    "oHoHo",
    "oHHHo",
    ".oHo.",
    "..o..",
])
STAR = R([
    "..o..",
    ".o:o.",
    "o:::o",
    ".o:o.",
    "..o..",
])
SPARKLE = R([
    ".K.",
    "KKK",
    ".K.",
])
BROKEN_SYRINGE = R([   # plunger end, a snapped glass barrel, shards and a leaking vaccine puddle
    "..o.............",
    ".o&o..ooooooo...",
    "o%&%oo^^^^^^^o..",
    "o#%#oo*****^^o.o",
    ".o#o.o*****^o.o&",
    "..o..oooooooo.oo",
    "....[**[***[[...",
])
PAW_POSTER = R([
    "ooooooooooooo",
    "oWWWWWWWWWWwo",
    "oWWWpWWWpWWwo",
    "oWpWpWWWpWpwo",
    "oWpWWWWWWWpwo",
    "oWWWWpppWWWwo",
    "oWWWpppppWWwo",
    "oWWWpppppWWwo",
    "oWWWWpWpWWWwo",
    "owwwwwwwwwwwo",
    "ooooooooooooo",
])
TABLE = R([            # steel exam table, top surface, front edge, two legs on castors
    "ooooooooooooooooooooooooooooooooooooo",
    "oKK&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%o",
    "o&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%%o",
    "o&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%%%o",
    "ooooooooooooooooooooooooooooooooooooo",
    "o%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#o",
    "o#################################%#o",
    "ooooooooooooooooooooooooooooooooooooo",
    "..o%#o.........................o%#o..",
    "..o%#o.........................o%#o..",
    "..o%#o.........................o%#o..",
    "..o%#o.........................o%#o..",
    "..o%#o.........................o%#o..",
    "..o%#o.........................o%#o..",
    "..o%#o.........................o%#o..",
    ".oo##oo.......................oo##oo.",
    ".o#oo#o.......................o#oo#o.",
    "..o..o.........................o..o..",
])


def _fill(rows, x0, y0, x1, y1, key):
    """Fill the inclusive box with key (background only)."""
    out = [list(r) for r in rows]
    for y in range(max(y0, 0), min(y1, len(out) - 1) + 1):
        for x in range(max(x0, 0), min(x1, len(out[0]) - 1) + 1):
            out[y][x] = key
    return [''.join(r) for r in out]


def background():
    w, h = WIN
    rows = ['_' * w] * h
    # back wall: pale tiles, teal wainscot, dark baseboard
    rows = _fill(rows, 0, 0, w - 1, WALL_H - 1, 'k')
    rows = _fill(rows, 0, 0, w - 1, 1, '%')
    for x in range(5, w, 10):
        rows = _fill(rows, x, 2, x, 15, 'n')
    rows = _fill(rows, 0, 9, w - 1, 9, 'n')
    rows = _fill(rows, 0, 16, w - 1, 16, '~')
    rows = _fill(rows, 0, 17, w - 1, 23, '$')
    rows = _fill(rows, 0, 17, w - 1, 17, '<')
    rows = _fill(rows, 0, 24, w - 1, 25, '~')
    # floor: white tiles with grout, a cool shadow band under the wall
    for y in range(WALL_H, h):
        for x in range(w):
            if (y - WALL_H) % 11 == 10 or x % 11 == 3:
                rows = _fill(rows, x, y, x, y, '0')
    rows = _fill(rows, 0, WALL_H, w - 1, WALL_H, 'n')
    # the open doorway: wooden frame, warm light inside and spilling onto the floor
    rows = _fill(rows, 4, 2, 37, WALL_H - 1, 'o')
    rows = _fill(rows, 5, 3, 36, WALL_H - 1, '\\')
    rows = _fill(rows, 7, 5, 34, WALL_H - 1, 'o')
    rows = _fill(rows, 8, 6, 33, WALL_H - 1, '8')
    rows = _fill(rows, 5, 3, 36, 3, '+')
    for i, y in enumerate(range(WALL_H, WALL_H + 12)):
        rows = _fill(rows, 8 - i, y, 33 + i, y, '8')
    # the table's shadow on the tiles
    rows = _fill(rows, 38, 58, 76, 59, 'n')
    return rows


def scene():
    rows = background()
    rows = overlay(rows, PAW_POSTER, 88, 4)
    rows = overlay(rows, BOGDAN, 3, 19)
    rows = overlay(rows, bianca(), 16, 23)
    rows = overlay(rows, TABLE, 38, 41)
    rows = overlay(rows, pluto(), 41, 20)
    vet = flip_h(VP.CLIPS['die'][-1])          # the Vet's own KO frame (hand-drawn), head to the right
    rows = overlay(rows, vet[18:], 58, 47)
    rows = overlay(rows, BROKEN_SYRINGE, 38, 60)
    for x, y in ((87, 43), (95, 39), (103, 43)):
        rows = overlay(rows, STAR, x, y)
    for x, y in ((39, 16), (33, 9)):
        rows = overlay(rows, HEART, x, y)
    for x, y in ((73, 16), (40, 30), (78, 27)):
        rows = overlay(rows, SPARKLE, x, y)
    return rows


def image():
    """Figures over the opaque background, so the translucent syringe glass shows the tiles and the photo stays opaque."""
    return Image.alpha_composite(V.image(background()), V.image(scene()))


def preview(scale=6):
    """The picture at 6x beside a mock of the Ammonomicon page (grey page, photo at ~5.25x, tape on the corners)
    and a 1x copy. Docs only, never shipped."""
    pic = image()
    big = pic.resize((WIN[0] * scale, WIN[1] * scale), Image.NEAREST)
    gs = 5
    shown = pic.resize((WIN[0] * gs, WIN[1] * gs), Image.NEAREST)
    pw, ph = shown.width + 160, shown.height + 200
    page = Image.new('RGBA', (pw, ph), (0x9D, 0x9B, 0x93, 255))
    from PIL import ImageDraw
    d = ImageDraw.Draw(page)
    d.rectangle((0, 0, pw - 1, ph - 1), outline=(0x5A, 0x2A, 0x2E, 255), width=10)
    ox, oy = 80, 60
    page.paste(shown, (ox, oy))
    tape = (0xE8, 0xE2, 0xCC, 255)
    for cx, cy in ((ox, oy), (ox + shown.width, oy), (ox, oy + shown.height), (ox + shown.width, oy + shown.height)):
        d.polygon([(cx - 34, cy - 10), (cx - 10, cy - 34), (cx + 34, cy + 10), (cx + 10, cy + 34)], fill=tape)
    d.text((ox, oy + shown.height + 60), 'KILLED BY  Nobody. You did great!', fill=(0x7A, 0x14, 0x14, 255))
    gap = 24
    W = big.width + gap + page.width + gap + WIN[0] + gap
    H = max(big.height, page.height) + 2 * gap
    out = Image.new('RGBA', (W, H), (0x20, 0x20, 0x24, 255))
    out.paste(big, (gap, gap))
    out.paste(page, (big.width + 2 * gap, gap))
    out.paste(pic, (big.width + page.width + 3 * gap, gap))
    return out


def write(project):
    win = os.path.join(project, 'Resources', 'past_win_pic.png')
    prev = os.path.join(project, 'docs', 'preview', 'win-pic-preview.png')
    os.makedirs(os.path.dirname(prev), exist_ok=True)
    image().save(win)
    preview().save(prev)
    return win, prev


if __name__ == '__main__':
    for p in write(V.PROJECT):
        print('win pic   ', p)
