// GENERATED by tools/cast_layout.py from the pose modules. Do not edit by hand.
namespace PlutoVetVisit
{
    public static class CastLayout
    {
        public const string NPC_ROOT = "PlutoVetVisit/Resources/Npcs";
        public const string TECH_ROOT = "PlutoVetVisit/Resources/Enemies/tech";
        public const int TECH_W = 32, TECH_H = 32;
        public const int TECH_HIT_X = 8, TECH_HIT_Y = 0, TECH_HIT_W = 12, TECH_HIT_H = 26;
        public const int TECH_SHOOT_X = 30, TECH_SHOOT_Y = 10;
        public static readonly string[] TECH_CLIPS = { "idle", "move", "tell", "fire", "die" };
        public static readonly int[] TECH_FRAMES = { 4, 6, 3, 3, 6 };
        public const string STECH_ROOT = "PlutoVetVisit/Resources/Enemies/stech";
        public const int STECH_W = 32, STECH_H = 32;
        public const int STECH_HIT_X = 8, STECH_HIT_Y = 0, STECH_HIT_W = 12, STECH_HIT_H = 26;
        public const int STECH_SHOOT_X = 30, STECH_SHOOT_Y = 10;
        public static readonly string[] STECH_CLIPS = { "idle", "move", "tell", "fire", "die" };
        public static readonly int[] STECH_FRAMES = { 4, 6, 3, 3, 6 };
        public const string NURSE_ROOT = "PlutoVetVisit/Resources/Enemies/nurse";
        public const int NURSE_W = 48, NURSE_H = 40;
        public const int NURSE_HIT_X = 11, NURSE_HIT_Y = 0, NURSE_HIT_W = 21, NURSE_HIT_H = 38;
        public const int NURSE_SHOOT_X = 44, NURSE_SHOOT_Y = 16;
        public static readonly string[] NURSE_CLIPS = { "idle", "move", "tell", "fire", "net", "die" };
        public static readonly int[] NURSE_FRAMES = { 4, 6, 3, 3, 4, 8 };
        public const string VET_ROOT = "PlutoVetVisit/Resources/Boss/vet";
        public const int VET_W = 48, VET_H = 40;
        public const int VET_HIT_X = 7, VET_HIT_Y = 0, VET_HIT_W = 20, VET_HIT_H = 39;
        public const int VET_SHOOT_X = 45, VET_SHOOT_Y = 20;
        public static readonly string[] VET_CLIPS = { "idle", "move", "tell", "fire", "intro", "die" };
        public static readonly int[] VET_FRAMES = { 5, 6, 4, 4, 8, 8 };
        public static readonly string[] VET_MASK_CLIPS = { "mask_on", "mask_idle", "mask_move", "mask_tell", "mask_fire", "mask_die" };
        public static readonly int[] VET_MASK_FRAMES = { 5, 5, 6, 4, 4, 8 };
        public static readonly NpcSpec[] NPCS = {
            new NpcSpec("pluto_npc_bogdan", "bogdan", 48, 40, new[] { "idle", "walk", "walk_free" }, new[] { 2, 6, 6 }),
            new NpcSpec("pluto_npc_bianca", "bianca", 48, 40, new[] { "idle", "walk", "wave" }, new[] { 2, 6, 4 }),
            new NpcSpec("pluto_npc_receptionist", "receptionist", 32, 40, new[] { "idle", "talk" }, new[] { 2, 2 }),
            new NpcSpec("pluto_npc_rex", "rex", 24, 24, new[] { "idle" }, new[] { 2 }),
            new NpcSpec("pluto_npc_grandma", "grandma", 24, 24, new[] { "loaf" }, new[] { 2 }),
        };
    }

    public class NpcSpec
    {
        public string Name, Folder;
        public int W, H;
        public string[] Clips;
        public int[] Frames;
        public NpcSpec(string name, string folder, int w, int h, string[] clips, int[] frames)
        {
            Name = name; Folder = folder; W = w; H = h; Clips = clips; Frames = frames;
        }
    }
}
